### PR TITLE
Docs - Add example using LiteLLM Proxy with Flowise

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Doc - Add example on using Flowise with LiteLLM Proxy

Hi, I'm the maintainer of [LiteLLM](https://github.com/BerriAI/litellm) - made a PR to show how to use Flowise with LiteLLM Proxy

## Why use LiteLLM Proxy ? 
Use [LiteLLM Proxy](https://docs.litellm.ai/docs/simple_proxy) to:
- Load balance Azure OpenAI/LLM endpoints
- Call 100+ LLMs in the OpenAI Format 
- Use Virtual Keys to set budgets, rate limits and track usage

## Related issues:
 - https://github.com/FlowiseAI/Flowise/discussions/1457
 - https://github.com/FlowiseAI/Flowise/issues/2814
 - https://github.com/FlowiseAI/Flowise/issues/1863

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@HenryHengZJ @toi500 can I get a review on this PR? Happy to make edits based on your suggestions

**Comment by HenryHengZJ** [comment]
Appreciate the docs! So after LiteLLM Proxy is up and running, user just need to specify the base url like below, right?
image

**Comment by HenryHengZJ** [comment]
Any base options needed, bascially headers

**Comment by ishaan-jaff** [comment]
> bascially headers

Headers are optional

**Comment by ishaan-jaff** [comment]
Anything else needed to merge @HenryHengZJ ?

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
thank you @ishaan-jaff !

**Pull request merged**
