### PR TITLE
Adding to Documentation

### PR DESCRIPTION
**Pull request by dewitt4**
I am adding to the documentation as I use FlowiseAI to contribute and help my own understanding 

I only used markdown and made sure to follow naming conventions

### CODE REVIEW

**Comment by dewitt4** [comment]
Great thanks! @HenryHengZJ  - I will add to SUMMARY.md  and keep adding to the docs as I learn FlowiseAI :)

**Comment by dewitt4** [comment]
Updated SUMMARY.md with new page files

**Comment by dewitt4** [comment]
Submitting new Pull Request

**Comment by dewitt4** [comment]
SUMMARY.md now updated to reflect changed page files

**Review by HenryHengZJ — APPROVED** [review]

**Pull request merged**
