### PR TITLE
Add Hugging Face deployment

### PR DESCRIPTION
**Pull request by lucianotonet**
### Objective of the Pull Request
This pull request aims to add documentation for deploying Flowise on Hugging Face Spaces. It provides a step-by-step guide to creating a new space, setting environment variables, creating a Dockerfile, and building the app on Hugging Face.

### Changes Made
1. **Added Hugging Face Deployment Guide**: A new file `hugging-face.md` has been created in the `deployment` directory, containing detailed instructions for deploying Flowise on Hugging Face Spaces.
2. **Updated Summary and README**: The `SUMMARY.md` and `deployment/README.md` files have been updated to include a link to the new Hugging Face deployment guide.

### Detailed Changes
- Added a new section for Hugging Face deployment in `deployment/hugging-face.md`, including:
  - Creating a new space on Hugging Face.
  - Setting environment variables (optional).
  - Creating a Dockerfile with specific instructions.
  - Building the app and accessing it once built.
- Updated `SUMMARY.md` and `deployment/README.md` to include a link to the new Hugging Face deployment guide.

### Impact
These changes provide clear and concise instructions for users who wish to deploy Flowise on Hugging Face Spaces. It enhances the documentation by offering a new deployment option, making it easier for users to leverage this platform.

### Preview ([check here](https://docs.flowiseai.com/~/revisions/Rl3QGsw2Y4epIFTksJCs/deployment/hugging-face))
The new guide includes steps such as:
- Signing in to Hugging Face and creating a new space with preferred settings.
- Optionally setting environment variables and secrets.
- Creating a Dockerfile with specific instructions for Flowise.
- Committing the file and building the app on Hugging Face.

### Conclusion
This addition to the documentation broadens the deployment options for Flowise, catering to users who prefer or require Hugging Face Spaces. It aligns with the project's goal of providing versatile and accessible deployment solutions.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
thanks @lucianotonet for the details explanation, appreciated!!

**Comment by chungyau97** [comment]
Hi @lucianotonet,

I followed the steps accordingly but I'm not able to deploy successfully.
image

Here's the link to my HF spaces: https://huggingface.co/spaces/chungyau97/chungyau97-flowise

**Comment by lucianotonet** [comment]
You are correct @chungyau97. Port 7860 is required on HF, but I think saving this variable **[shouldn't be optional](https://github.com/FlowiseAI/FlowiseDocs/pull/28/files#diff-f68c71ff77c83abb17b4400894264a381b4d27dd48a890e31bad516728123587R15)**. 
Can you check, please?

**Comment by chungyau97** [comment]
Hi @lucianotonet,

Thanks for point that mistake, appreciate it a lot. 
Fix it in this [Flowise Docs PR 29](<https://github.com/FlowiseAI/FlowiseDocs/pull/29>)

**Pull request merged**
